# Generated by Django 3.2.4 on 2022-09-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transactionCategory',
            field=models.CharField(choices=[('FD', 'FOOD & DRINKS'), ('SH', 'SHOPPING'), ('HO', 'HOUSING'), ('TR', 'TRANSPORTATION'), ('VE', 'VEHICLE'), ('LE', 'LIFE & ENTERTAINMENT'), ('PC', 'PC, COMMUNICATION'), ('FE', 'FINANCIAL EXPENSES'), ('IV', 'INVESTMENT'), ('IC', 'INCOME'), ('OT', 'OTHERS')], default='FD', max_length=2),
            preserve_default=False,
        ),
    ]
