# Generated by Django 3.2.4 on 2022-09-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_transaction_transactioncategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionCategory',
            field=models.CharField(choices=[('FD', 'Food & Drinks'), ('SH', 'Shopping'), ('HO', 'Housing'), ('TR', 'Transportation'), ('VE', 'Vehicle'), ('LE', 'Life & Entertainment'), ('PC', 'PC, Communication'), ('FE', 'Financial Investment'), ('IV', 'Investment'), ('IC', 'Income'), ('OT', 'Others')], max_length=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionType',
            field=models.CharField(choices=[('S', 'In'), ('E', 'Expenses')], max_length=1),
        ),
    ]
