# Generated by Django 3.2.4 on 2022-09-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20220907_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionCategory',
            field=models.CharField(choices=[('Food & Drinks', 'Food & Drinks'), ('Shoppin', 'Shopping'), ('Housing', 'Housing'), ('Transportation', 'Transportation'), ('Vehicle', 'Vehicle'), ('Life & Entertainment', 'Life & Entertainment'), ('PC, Communication', 'PC, Communication'), ('Financial Investment', 'Financial Investment'), ('Investment', 'Investment'), ('Income', 'Income'), ('Others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionType',
            field=models.CharField(choices=[('S', 'Savings'), ('E', 'Expenses')], max_length=1),
        ),
    ]
