# Generated by Django 3.2.4 on 2022-09-10 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_transaction_transactioncategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='balance',
            new_name='currentBalance',
        ),
    ]
