# Generated by Django 3.2.4 on 2022-09-10 03:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_balancerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancerecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
